# -*- coding: utf-8 -*-
"""Module - Logistic Regression .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AHZ-5PArvmqj_ZTHeewRlnqdue_WwE7s
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

def train_logistic_model(data, target_column):

    # Split the data into features (X) and target (y)
    X = data.drop(columns=[target_column])
    y = data[target_column]

    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Initialize and train the Logistic Regression model
    model = LogisticRegression()
    model.fit(X_train, y_train)

    # Predict on test data
    y_pred = model.predict(X_test)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)

    # Return the trained model and accuracy
    return model, accuracy



